### ISSUE TITLE
learn android

### ISSUE THREAD

**Issue by saeedmpt** [axet/moved#1]
Hello. I saw one of your projects. I want to code you like that. But I do not know where to start and what resources to study to get to your knowledge level?

**Comment by axet** [comment]
Like any art, you have to master and remaster what you already done. Music, painting, biking, android...

What you did once, you have to redo again until it meet your imagination. Easy to do with source code - just rewrite it from scratch again and again, if it is not modular / simple enough.

Imagination -> keep imagine it and let your hands do what you see -> masterpiece (until you realize how actually bad it is and you remake it again).

Here is no secrets, android - like anything else here on earth. Here some places in Universe where you don't have to study, because you already know it all, but you are here, and you have to study and repeat to get decent results. Google and stackoverflow.com - my sources for android tricks, my imagination - my goals. You have to enjoy every moment - or fail.
